trigger:
  - dev
  - main

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "20.x"
      displayName: "Install Node.js"

    - script: |
        npm install
      displayName: "Install dependencies"

    - script: |
        npm run test:ci
      displayName: "Run tests"
      continueOnError: true

    - script: |
        echo "Building application..."
        npm run build
        echo "Copying web.config to dist..."
        cp web.config dist/
        echo "Contents of dist directory:"
        ls -la dist/
      displayName: 'Build and prepare dist'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
        replaceExistingArchive: true
      displayName: 'Archive Files'

    - script: |
        echo "Archive created. Contents:"
        ls -la $(Build.ArtifactStagingDirectory)
        echo "Archive size:"
        du -sh $(Build.ArtifactStagingDirectory)/*
        echo "Contents of zip file:"
        unzip -l $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Debug: Check artifact contents'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployToStaging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployToStaging
    pool:
      vmImage: ubuntu-latest
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          
          - task: AzureWebApp@1
            timeoutInMinutes: 10
            inputs:
              appType: webApp
              azureSubscription: 'incident-reporting-system'
              appName: 'incident-report-system'
              package: '$(System.ArtifactsDirectory)/**/*.zip'
              appSettings: |
                -NODE_ENV production
                -WEBSITE_NODE_DEFAULT_VERSION 20.x