trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - script: |
      npm run test:ci
    displayName: "Run tests"
    continueOnError: true

  - task: PublishTestResults@2
    displayName: "Publish test results"
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "junit.xml"
      mergeTestResults: true
      failTaskOnFailedTests: false
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@2
    displayName: "Publish code coverage"
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml"
      pathToSources: "$(Build.SourcesDirectory)"
      failIfCoverageEmpty: false
    condition: succeededOrFailed()

  - script: |
      if [ $AGENT_JOBSTATUS == "Failed" ]; then
        exit 1
      fi
    displayName: 'Check for test failures'
    condition: always()